### ISSUE TITLE
Error when running calibration

### ISSUE THREAD

**Issue by coheonsb** [eborghi10/spot_quadruped_ros#11]
`roslaunch spotmicro_config calibration.launch`

I get this error, can you tell me the cause?

I installed ros on Ubuntu 18.04 on Raspberry Pi 4.

```
 logging to /home/pi/.ros/log/13a98a24-d1fb-11ed-9849-9bba06f77d50/roslaunch-raspberrypi-2616.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://raspberrypi:37643/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.15

NODES
  /
    i2cpwm_board (i2cpwm_board/i2cpwm_board)
    servo_move_keyboard (servo_move_keyboard/servoMoveKeyboard.py)

auto-starting new master
process[master]: started with pid [2624]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 13a98a24-d1fb-11ed-9849-9bba06f77d50
process[rosout-1]: started with pid [2634]
started core service [/rosout]
ERROR: cannot launch node of type [i2cpwm_board/i2cpwm_board]: Cannot locate node of type [i2cpwm_board] in package [i2cpwm_board]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [servo_move_keyboard/servoMoveKeyboard.py]: servo_move_keyboard
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/pi/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share

```

**Comment by eborghi10** [comment]
Hey, sorry if the documentation is not quite clear. This error:

> ERROR: cannot launch node of type [i2cpwm_board/i2cpwm_board]: Cannot locate node of type [i2cpwm_board] in package [i2cpwm_board]. Make sure file exists in package path and permission is set to executable (chmod +x)
> ERROR: cannot launch node of type [servo_move_keyboard/servoMoveKeyboard.py]: servo_move_keyboard

may happen for different reasons. First, check if your packages listed in [this README](https://github.com/eborghi10/spot_quadruped_ros/blob/master/docs/software.md#workspace-setup) are correct. For example, make sure that the package [`i2c_pwd_board`](https://github.com/eborghi10/i2c_pwm_board) is on the branch `master`.

If that doesn't work, [the executable needs execution permissions](https://www.theconstructsim.com/ros-beginner-mistakes-1-missing-execute-permission-on-the-python-file/) but I doubt so.

**Comment by coheonsb** [comment]
Yes I seem to have set all branches equal to document.

 The i2c_pwd_board branch in the example only exists as master, so it was not checkout separately after cloning.

also I set everything under the src folder to 777.

**Comment by eborghi10** [comment]
> ERROR: cannot launch node of type [i2cpwm_board/i2cpwm_board]: Cannot locate node of type [i2cpwm_board] in package [i2cpwm_board]. Make sure file exists in package path and permission is set to the xecutable (chmod +x)

The node `i2cpwm_board` was renamed to `i2cpwm_controller`, see the commit with the fix [here](https://github.com/eborghi10/robots/commit/838504894c05d4e90a41afa1f52e3911cf31d61f).

> ERROR: cannot launch node of type [servo_move_keyboard/servoMoveKeyboard.py]: servo_move_keyboard

This node was not found because the package was not compiled. Use [this package](https://github.com/mike4192/spotMicro/tree/master/servo_move_keyboard).

**Comment by cheonseulbyeol** [comment]
thx a lot 😍 I will try again

**Comment by coheonsb** [comment]
Thx a lot 
I will try again
